name: smoke-local
on:
  workflow_dispatch:

jobs:
  ping-runner:
    runs-on: self-hosted
    steps:
      - name: Checagens b√°sicas
        run: |
          whoami
          hostname -A || hostname -I
          docker ps
          docker compose version || true
